### ISSUE TITLE
Not1MM closing when pressing SPACE

### ISSUE THREAD

**Issue by py4xx** [mbridak/not1mm#141] opened 2024-09-18 20:02 UTC
**Describe the bug**

_**With or without call in the callsign field, when you press space, not1mm simply closes.**_

**To Reproduce**

**_2. Click on SPACE key_**

**Expected behavior**

**_Let the cursor go to the next field._**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - _**Linux UBUNTU**_
 - Version [e.g. 22]  **_24.04_**

**Additional context**

**Comment by mbridak** [comment] 2024-09-18 20:10
@py4xx Hello, I can't reproduce this. It may be dependent on the contest selected at the time.
Could you tell me which one was used?

**Comment by mbridak** [comment] 2024-09-21 16:11
@py4xx I'll be closing this soon if I don't get a little more info.
I need to know which contest was loaded when this happened.
It would help even more if you launched it from a terminal, then paste in the traceback it spits out when it died.

**Comment by mbridak** [comment] 2024-09-22 16:11
closing for lack of followup.

**Closed by mbridak** 2024-09-22 16:11 UTC
Labels: bug

**Comment by py4xx** [comment] 2024-09-24 21:08
Hi Michael...


Sorry I didn't respond sooner, but I was really busy... The contest was the
CWT. Whenever I pressed space, the program closed. Fort 73

Em dom., 22 de set. de 2024 às 13:12, Michael Bridak <
***@***.***> escreveu:

**Comment by mbridak** [comment] 2024-09-25 00:47
Thanks. Fixed and pushed.
